name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version to release (e.g. 2.4.0)'
        required: true
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: shopstic/jdk11-sbt-fdb-server:1.4.4
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'shopstic/chopsticks' }}
    steps:
      - name: Install git
        run: apt-get install git -y
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            /root/.cache/coursier
            /root/.sbt
          key: build-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*.scala') }}
      - name: Setup FDB cluster file and start FDB
        run: mkdir -p ~/.fdb && cp /etc/foundationdb/fdb.cluster ~/.fdb/cluster.file && service foundationdb start
      - name: Install GPG
        run: apt update && apt install -y gnupg
      - name: Setup git credentials
        run: |
          git config --global user.name 'Auto Deployer'
          git config --global user.email 'auto-deployer@shopstic.github.com'
      - name: Release
        env:
          FATAL_WARNINGS: "true"
          PUBLISH_TO_SONATYPE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          export GPG_TTY=$(tty)
          sbt "release release-version ${{ github.event.inputs.releaseVersion }} with-defaults"
